### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by at15** [cit-lab/apm-collector#8]
1. the SigarService got init twice, fixed, call the init at start
2. got error in kdb client
````
error sending machine logclass java.util.ConcurrentModificationExceptionnullnull
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:95)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.Gson.toJson(Gson.java:593)
	at com.google.gson.Gson.toJson(Gson.java:572)
	at com.google.gson.Gson.toJson(Gson.java:527)
	at com.google.gson.Gson.toJson(Gson.java:507)
	at org.kairosdb.client.builder.MetricBuilder.build(MetricBuilder.java:109)
	at org.kairosdb.client.AbstractClient.pushMetrics(AbstractClient.java:130)
	at cn.edu.sjtu.cit.apm.collector.kairosdb.KDBClient.send(KDBClient.java:94)
	at cn.edu.sjtu.cit.apm.collector.kairosdb.KDBClient.sendMachineDouble(KDBClient.java:49)
	at cn.edu.sjtu.cit.apm.collector.system.MachineProbe$1.run(MachineProbe.java:28)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
````

fixed using `synchronized` keyword

**Comment by at15** [comment]
I think better change kdbclient to a non statci class, and use it in every single thread

**Comment by at15** [comment]
using `synchronized` is causing #9

**Comment by at15** [comment]
we are using the telnet to put metrics now, so this is no longer a problem
